USE [Northwind]
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Categories_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Categories_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Categories_SelectViewByPK] @CategoryID = 1

CREATE PROCEDURE [dbo].[PR_Categories_SelectViewByPK]

		@CategoryID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Categories].[CategoryID],
		[dbo].[Categories].[CategoryName],
		[dbo].[Categories].[Description],
		[dbo].[Categories].[Picture]
FROM  [dbo].[Categories]

WHERE [dbo].[Categories].[CategoryID] = @CategoryID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_CustomerCustomerDemo_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_CustomerCustomerDemo_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_CustomerCustomerDemo_SelectViewByPK] @CustomerID = 'CustomerID', @CustomerTypeID = 'CustomerTypeID'

CREATE PROCEDURE [dbo].[PR_CustomerCustomerDemo_SelectViewByPK]

		@CustomerID     		nchar (5),
		@CustomerTypeID 		nchar (10)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[CustomerCustomerDemo].[CustomerID],
		[dbo].[Customers].[CompanyName],
		[dbo].[Customers].[ContactName],
		[dbo].[CustomerCustomerDemo].[CustomerTypeID]
FROM  [dbo].[CustomerCustomerDemo]
INNER JOIN [dbo].[Customers]
ON [dbo].[CustomerCustomerDemo].[CustomerID] = [dbo].[Customers].[CustomerID]

WHERE [dbo].[CustomerCustomerDemo].[CustomerID] = @CustomerID
AND [dbo].[CustomerCustomerDemo].[CustomerTypeID] = @CustomerTypeID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_CustomerDemographics_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_CustomerDemographics_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_CustomerDemographics_SelectViewByPK] @CustomerTypeID = 'CustomerTypeID'

CREATE PROCEDURE [dbo].[PR_CustomerDemographics_SelectViewByPK]

		@CustomerTypeID 		nchar (10)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[CustomerDemographics].[CustomerTypeID],
		[dbo].[CustomerDemographics].[CustomerDesc]
FROM  [dbo].[CustomerDemographics]

WHERE [dbo].[CustomerDemographics].[CustomerTypeID] = @CustomerTypeID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Customers_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Customers_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Customers_SelectViewByPK] @CustomerID = 'CustomerID'

CREATE PROCEDURE [dbo].[PR_Customers_SelectViewByPK]

		@CustomerID 		nchar (5)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Customers].[CustomerID],
		[dbo].[Customers].[CompanyName],
		[dbo].[Customers].[ContactName],
		[dbo].[Customers].[ContactTitle],
		[dbo].[Customers].[Address],
		[dbo].[Customers].[City],
		[dbo].[Customers].[Region],
		[dbo].[Customers].[PostalCode],
		[dbo].[Customers].[Country],
		[dbo].[Customers].[Phone],
		[dbo].[Customers].[Fax]
FROM  [dbo].[Customers]

WHERE [dbo].[Customers].[CustomerID] = @CustomerID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Employees_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Employees_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Employees_SelectViewByPK] @EmployeeID = 1

CREATE PROCEDURE [dbo].[PR_Employees_SelectViewByPK]

		@EmployeeID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Employees].[EmployeeID],
		[dbo].[Employees].[LastName] AS [Employees_LastName],
		[dbo].[Employees].[FirstName] AS [Employees_FirstName],
		[dbo].[Employees].[Title],
		[dbo].[Employees].[TitleOfCourtesy],
		[dbo].[Employees].[BirthDate],
		[dbo].[Employees].[HireDate],
		[dbo].[Employees].[Address],
		[dbo].[Employees].[City],
		[dbo].[Employees].[Region],
		[dbo].[Employees].[PostalCode],
		[dbo].[Employees].[Country],
		[dbo].[Employees].[HomePhone],
		[dbo].[Employees].[Extension],
		[dbo].[Employees].[Photo],
		[dbo].[Employees].[Notes],
		[dbo].[Employees].[ReportsTo],
		[ReportsTo_Employees].[LastName] AS [ReportsTo_Employees_LastName],
		[ReportsTo_Employees].[FirstName] AS [ReportsTo_Employees_FirstName],
		[dbo].[Employees].[PhotoPath]
FROM  [dbo].[Employees]
LEFT OUTER JOIN [dbo].[Employees] AS [ReportsTo_Employees]
ON [dbo].[Employees].[ReportsTo] = [ReportsTo_Employees].[EmployeeID]

WHERE [dbo].[Employees].[EmployeeID] = @EmployeeID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_EmployeeTerritories_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_EmployeeTerritories_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_EmployeeTerritories_SelectViewByPK] @EmployeeID = 1, @TerritoryID = 'TerritoryID'

CREATE PROCEDURE [dbo].[PR_EmployeeTerritories_SelectViewByPK]

		@EmployeeID  		int,
		@TerritoryID 		nvarchar (20)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[EmployeeTerritories].[EmployeeID],
		[dbo].[Employees].[LastName],
		[dbo].[Employees].[FirstName],
		[dbo].[EmployeeTerritories].[TerritoryID],
		[dbo].[Territories].[TerritoryDescription]
FROM  [dbo].[EmployeeTerritories]
INNER JOIN [dbo].[Employees]
ON [dbo].[EmployeeTerritories].[EmployeeID] = [dbo].[Employees].[EmployeeID]
INNER JOIN [dbo].[Territories]
ON [dbo].[EmployeeTerritories].[TerritoryID] = [dbo].[Territories].[TerritoryID]

WHERE [dbo].[EmployeeTerritories].[EmployeeID] = @EmployeeID
AND [dbo].[EmployeeTerritories].[TerritoryID] = @TerritoryID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Order Details_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Order Details_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Order Details_SelectViewByPK] @OrderID = 1, @ProductID = 1

CREATE PROCEDURE [dbo].[PR_Order Details_SelectViewByPK]

		@OrderID   		int,
		@ProductID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Order Details].[OrderID],
		[dbo].[Order Details].[ProductID],
		[dbo].[Products].[ProductName],
		[dbo].[Order Details].[UnitPrice],
		[dbo].[Order Details].[Quantity],
		[dbo].[Order Details].[Discount]
FROM  [dbo].[Order Details]
INNER JOIN [dbo].[Products]
ON [dbo].[Order Details].[ProductID] = [dbo].[Products].[ProductID]

WHERE [dbo].[Order Details].[OrderID] = @OrderID
AND [dbo].[Order Details].[ProductID] = @ProductID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Orders_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Orders_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Orders_SelectViewByPK] @OrderID = 1

CREATE PROCEDURE [dbo].[PR_Orders_SelectViewByPK]

		@OrderID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Orders].[OrderID],
		[dbo].[Orders].[CustomerID],
		[dbo].[Customers].[CompanyName] AS [Customers_CompanyName],
		[dbo].[Customers].[ContactName],
		[dbo].[Orders].[EmployeeID],
		[dbo].[Employees].[LastName],
		[dbo].[Employees].[FirstName],
		[dbo].[Orders].[OrderDate],
		[dbo].[Orders].[RequiredDate],
		[dbo].[Orders].[ShippedDate],
		[dbo].[Orders].[ShipVia],
		[dbo].[Shippers].[CompanyName] AS [Shippers_CompanyName],
		[dbo].[Orders].[Freight],
		[dbo].[Orders].[ShipName],
		[dbo].[Orders].[ShipAddress],
		[dbo].[Orders].[ShipCity],
		[dbo].[Orders].[ShipRegion],
		[dbo].[Orders].[ShipPostalCode],
		[dbo].[Orders].[ShipCountry]
FROM  [dbo].[Orders]
LEFT OUTER JOIN [dbo].[Customers]
ON [dbo].[Orders].[CustomerID] = [dbo].[Customers].[CustomerID]
LEFT OUTER JOIN [dbo].[Employees]
ON [dbo].[Orders].[EmployeeID] = [dbo].[Employees].[EmployeeID]
LEFT OUTER JOIN [dbo].[Shippers]
ON [dbo].[Orders].[ShipVia] = [dbo].[Shippers].[ShipperID]

WHERE [dbo].[Orders].[OrderID] = @OrderID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Products_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Products_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Products_SelectViewByPK] @ProductID = 1

CREATE PROCEDURE [dbo].[PR_Products_SelectViewByPK]

		@ProductID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Products].[ProductID],
		[dbo].[Products].[ProductName],
		[dbo].[Products].[SupplierID],
		[dbo].[Suppliers].[CompanyName],
		[dbo].[Suppliers].[ContactName],
		[dbo].[Products].[CategoryID],
		[dbo].[Categories].[CategoryName],
		[dbo].[Products].[QuantityPerUnit],
		[dbo].[Products].[UnitPrice],
		[dbo].[Products].[UnitsInStock],
		[dbo].[Products].[UnitsOnOrder],
		[dbo].[Products].[ReorderLevel],
		[dbo].[Products].[Discontinued]
FROM  [dbo].[Products]
LEFT OUTER JOIN [dbo].[Categories]
ON [dbo].[Products].[CategoryID] = [dbo].[Categories].[CategoryID]
LEFT OUTER JOIN [dbo].[Suppliers]
ON [dbo].[Products].[SupplierID] = [dbo].[Suppliers].[SupplierID]

WHERE [dbo].[Products].[ProductID] = @ProductID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Region_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Region_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Region_SelectViewByPK] @RegionID = 1

CREATE PROCEDURE [dbo].[PR_Region_SelectViewByPK]

		@RegionID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Region].[RegionID],
		[dbo].[Region].[RegionDescription]
FROM  [dbo].[Region]

WHERE [dbo].[Region].[RegionID] = @RegionID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Shippers_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Shippers_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Shippers_SelectViewByPK] @ShipperID = 1

CREATE PROCEDURE [dbo].[PR_Shippers_SelectViewByPK]

		@ShipperID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Shippers].[ShipperID],
		[dbo].[Shippers].[CompanyName],
		[dbo].[Shippers].[Phone]
FROM  [dbo].[Shippers]

WHERE [dbo].[Shippers].[ShipperID] = @ShipperID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Suppliers_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Suppliers_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Suppliers_SelectViewByPK] @SupplierID = 1

CREATE PROCEDURE [dbo].[PR_Suppliers_SelectViewByPK]

		@SupplierID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Suppliers].[SupplierID],
		[dbo].[Suppliers].[CompanyName],
		[dbo].[Suppliers].[ContactName],
		[dbo].[Suppliers].[ContactTitle],
		[dbo].[Suppliers].[Address],
		[dbo].[Suppliers].[City],
		[dbo].[Suppliers].[Region],
		[dbo].[Suppliers].[PostalCode],
		[dbo].[Suppliers].[Country],
		[dbo].[Suppliers].[Phone],
		[dbo].[Suppliers].[Fax],
		[dbo].[Suppliers].[HomePage]
FROM  [dbo].[Suppliers]

WHERE [dbo].[Suppliers].[SupplierID] = @SupplierID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Territories_SelectViewByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Territories_SelectViewByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Territories_SelectViewByPK] @TerritoryID = 'TerritoryID'

CREATE PROCEDURE [dbo].[PR_Territories_SelectViewByPK]

		@TerritoryID 		nvarchar (20)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Territories].[TerritoryID],
		[dbo].[Territories].[TerritoryDescription],
		[dbo].[Territories].[RegionID],
		[dbo].[Region].[RegionDescription]
FROM  [dbo].[Territories]
INNER JOIN [dbo].[Region]
ON [dbo].[Territories].[RegionID] = [dbo].[Region].[RegionID]

WHERE [dbo].[Territories].[TerritoryID] = @TerritoryID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~