USE [Northwind]
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Categories_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Categories_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Categories_SelectByPK] @CategoryID = 1

CREATE PROCEDURE [dbo].[PR_Categories_SelectByPK]

		@CategoryID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Categories].[CategoryID],
		[dbo].[Categories].[CategoryName],
		[dbo].[Categories].[Description],
		[dbo].[Categories].[Picture]
FROM  [dbo].[Categories]

WHERE [dbo].[Categories].[CategoryID] = @CategoryID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_CustomerCustomerDemo_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_CustomerCustomerDemo_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_CustomerCustomerDemo_SelectByPK] @CustomerID = 'CustomerID', @CustomerTypeID = 'CustomerTypeID'

CREATE PROCEDURE [dbo].[PR_CustomerCustomerDemo_SelectByPK]

		@CustomerID     		nchar (5),
		@CustomerTypeID 		nchar (10)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[CustomerCustomerDemo].[CustomerID],
		[dbo].[CustomerCustomerDemo].[CustomerTypeID]
FROM  [dbo].[CustomerCustomerDemo]

WHERE [dbo].[CustomerCustomerDemo].[CustomerID] = @CustomerID
AND [dbo].[CustomerCustomerDemo].[CustomerTypeID] = @CustomerTypeID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_CustomerDemographics_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_CustomerDemographics_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_CustomerDemographics_SelectByPK] @CustomerTypeID = 'CustomerTypeID'

CREATE PROCEDURE [dbo].[PR_CustomerDemographics_SelectByPK]

		@CustomerTypeID 		nchar (10)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[CustomerDemographics].[CustomerTypeID],
		[dbo].[CustomerDemographics].[CustomerDesc]
FROM  [dbo].[CustomerDemographics]

WHERE [dbo].[CustomerDemographics].[CustomerTypeID] = @CustomerTypeID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Customers_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Customers_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Customers_SelectByPK] @CustomerID = 'CustomerID'

CREATE PROCEDURE [dbo].[PR_Customers_SelectByPK]

		@CustomerID 		nchar (5)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Customers].[CustomerID],
		[dbo].[Customers].[CompanyName],
		[dbo].[Customers].[ContactName],
		[dbo].[Customers].[ContactTitle],
		[dbo].[Customers].[Address],
		[dbo].[Customers].[City],
		[dbo].[Customers].[Region],
		[dbo].[Customers].[PostalCode],
		[dbo].[Customers].[Country],
		[dbo].[Customers].[Phone],
		[dbo].[Customers].[Fax]
FROM  [dbo].[Customers]

WHERE [dbo].[Customers].[CustomerID] = @CustomerID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Employees_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Employees_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Employees_SelectByPK] @EmployeeID = 1

CREATE PROCEDURE [dbo].[PR_Employees_SelectByPK]

		@EmployeeID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Employees].[EmployeeID],
		[dbo].[Employees].[LastName],
		[dbo].[Employees].[FirstName],
		[dbo].[Employees].[Title],
		[dbo].[Employees].[TitleOfCourtesy],
		[dbo].[Employees].[BirthDate],
		[dbo].[Employees].[HireDate],
		[dbo].[Employees].[Address],
		[dbo].[Employees].[City],
		[dbo].[Employees].[Region],
		[dbo].[Employees].[PostalCode],
		[dbo].[Employees].[Country],
		[dbo].[Employees].[HomePhone],
		[dbo].[Employees].[Extension],
		[dbo].[Employees].[Photo],
		[dbo].[Employees].[Notes],
		[dbo].[Employees].[ReportsTo],
		[dbo].[Employees].[PhotoPath]
FROM  [dbo].[Employees]

WHERE [dbo].[Employees].[EmployeeID] = @EmployeeID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_EmployeeTerritories_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_EmployeeTerritories_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_EmployeeTerritories_SelectByPK] @EmployeeID = 1, @TerritoryID = 'TerritoryID'

CREATE PROCEDURE [dbo].[PR_EmployeeTerritories_SelectByPK]

		@EmployeeID  		int,
		@TerritoryID 		nvarchar (20)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[EmployeeTerritories].[EmployeeID],
		[dbo].[EmployeeTerritories].[TerritoryID]
FROM  [dbo].[EmployeeTerritories]

WHERE [dbo].[EmployeeTerritories].[EmployeeID] = @EmployeeID
AND [dbo].[EmployeeTerritories].[TerritoryID] = @TerritoryID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Order Details_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Order Details_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Order Details_SelectByPK] @OrderID = 1, @ProductID = 1

CREATE PROCEDURE [dbo].[PR_Order Details_SelectByPK]

		@OrderID   		int,
		@ProductID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Order Details].[OrderID],
		[dbo].[Order Details].[ProductID],
		[dbo].[Order Details].[UnitPrice],
		[dbo].[Order Details].[Quantity],
		[dbo].[Order Details].[Discount]
FROM  [dbo].[Order Details]

WHERE [dbo].[Order Details].[OrderID] = @OrderID
AND [dbo].[Order Details].[ProductID] = @ProductID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Orders_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Orders_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Orders_SelectByPK] @OrderID = 1

CREATE PROCEDURE [dbo].[PR_Orders_SelectByPK]

		@OrderID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Orders].[OrderID],
		[dbo].[Orders].[CustomerID],
		[dbo].[Orders].[EmployeeID],
		[dbo].[Orders].[OrderDate],
		[dbo].[Orders].[RequiredDate],
		[dbo].[Orders].[ShippedDate],
		[dbo].[Orders].[ShipVia],
		[dbo].[Orders].[Freight],
		[dbo].[Orders].[ShipName],
		[dbo].[Orders].[ShipAddress],
		[dbo].[Orders].[ShipCity],
		[dbo].[Orders].[ShipRegion],
		[dbo].[Orders].[ShipPostalCode],
		[dbo].[Orders].[ShipCountry]
FROM  [dbo].[Orders]

WHERE [dbo].[Orders].[OrderID] = @OrderID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Products_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Products_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Products_SelectByPK] @ProductID = 1

CREATE PROCEDURE [dbo].[PR_Products_SelectByPK]

		@ProductID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Products].[ProductID],
		[dbo].[Products].[ProductName],
		[dbo].[Products].[SupplierID],
		[dbo].[Products].[CategoryID],
		[dbo].[Products].[QuantityPerUnit],
		[dbo].[Products].[UnitPrice],
		[dbo].[Products].[UnitsInStock],
		[dbo].[Products].[UnitsOnOrder],
		[dbo].[Products].[ReorderLevel],
		[dbo].[Products].[Discontinued]
FROM  [dbo].[Products]

WHERE [dbo].[Products].[ProductID] = @ProductID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Region_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Region_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Region_SelectByPK] @RegionID = 1

CREATE PROCEDURE [dbo].[PR_Region_SelectByPK]

		@RegionID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Region].[RegionID],
		[dbo].[Region].[RegionDescription]
FROM  [dbo].[Region]

WHERE [dbo].[Region].[RegionID] = @RegionID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Shippers_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Shippers_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Shippers_SelectByPK] @ShipperID = 1

CREATE PROCEDURE [dbo].[PR_Shippers_SelectByPK]

		@ShipperID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Shippers].[ShipperID],
		[dbo].[Shippers].[CompanyName],
		[dbo].[Shippers].[Phone]
FROM  [dbo].[Shippers]

WHERE [dbo].[Shippers].[ShipperID] = @ShipperID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Suppliers_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Suppliers_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Suppliers_SelectByPK] @SupplierID = 1

CREATE PROCEDURE [dbo].[PR_Suppliers_SelectByPK]

		@SupplierID 		int

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Suppliers].[SupplierID],
		[dbo].[Suppliers].[CompanyName],
		[dbo].[Suppliers].[ContactName],
		[dbo].[Suppliers].[ContactTitle],
		[dbo].[Suppliers].[Address],
		[dbo].[Suppliers].[City],
		[dbo].[Suppliers].[Region],
		[dbo].[Suppliers].[PostalCode],
		[dbo].[Suppliers].[Country],
		[dbo].[Suppliers].[Phone],
		[dbo].[Suppliers].[Fax],
		[dbo].[Suppliers].[HomePage]
FROM  [dbo].[Suppliers]

WHERE [dbo].[Suppliers].[SupplierID] = @SupplierID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Territories_SelectByPK]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Territories_SelectByPK]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Territories_SelectByPK] @TerritoryID = 'TerritoryID'

CREATE PROCEDURE [dbo].[PR_Territories_SelectByPK]

		@TerritoryID 		nvarchar (20)

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Territories].[TerritoryID],
		[dbo].[Territories].[TerritoryDescription],
		[dbo].[Territories].[RegionID]
FROM  [dbo].[Territories]

WHERE [dbo].[Territories].[TerritoryID] = @TerritoryID

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~