USE [Northwind]
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Alphabetical list of products_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Alphabetical list of products_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Alphabetical list of products_SelectAll]

CREATE PROCEDURE [dbo].[PR_Alphabetical list of products_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Alphabetical list of products].[ProductID],
		[dbo].[Alphabetical list of products].[ProductName],
		[dbo].[Alphabetical list of products].[SupplierID],
		[dbo].[Alphabetical list of products].[CategoryID],
		[dbo].[Alphabetical list of products].[QuantityPerUnit],
		[dbo].[Alphabetical list of products].[UnitPrice],
		[dbo].[Alphabetical list of products].[UnitsInStock],
		[dbo].[Alphabetical list of products].[UnitsOnOrder],
		[dbo].[Alphabetical list of products].[ReorderLevel],
		[dbo].[Alphabetical list of products].[Discontinued],
		[dbo].[Alphabetical list of products].[CategoryName]
FROM  [dbo].[Alphabetical list of products]

ORDER BY [dbo].[Alphabetical list of products].[ProductName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Categories_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Categories_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Categories_SelectAll]

CREATE PROCEDURE [dbo].[PR_Categories_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Categories].[CategoryID],
		[dbo].[Categories].[CategoryName],
		[dbo].[Categories].[Description],
		[dbo].[Categories].[Picture]
FROM  [dbo].[Categories]

ORDER BY [dbo].[Categories].[CategoryName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Category Sales for 1997_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Category Sales for 1997_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Category Sales for 1997_SelectAll]

CREATE PROCEDURE [dbo].[PR_Category Sales for 1997_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Category Sales for 1997].[CategoryName],
		[dbo].[Category Sales for 1997].[CategorySales]
FROM  [dbo].[Category Sales for 1997]

ORDER BY [dbo].[Category Sales for 1997].[CategoryName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Current Product List_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Current Product List_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Current Product List_SelectAll]

CREATE PROCEDURE [dbo].[PR_Current Product List_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Current Product List].[ProductID],
		[dbo].[Current Product List].[ProductName]
FROM  [dbo].[Current Product List]

ORDER BY [dbo].[Current Product List].[ProductName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Customer and Suppliers by City_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Customer and Suppliers by City_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Customer and Suppliers by City_SelectAll]

CREATE PROCEDURE [dbo].[PR_Customer and Suppliers by City_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Customer and Suppliers by City].[City],
		[dbo].[Customer and Suppliers by City].[CompanyName],
		[dbo].[Customer and Suppliers by City].[ContactName],
		[dbo].[Customer and Suppliers by City].[Relationship]
FROM  [dbo].[Customer and Suppliers by City]

ORDER BY [dbo].[Customer and Suppliers by City].[CompanyName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_CustomerCustomerDemo_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_CustomerCustomerDemo_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_CustomerCustomerDemo_SelectAll]

CREATE PROCEDURE [dbo].[PR_CustomerCustomerDemo_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[CustomerCustomerDemo].[CustomerID],
		[dbo].[Customers].[CompanyName],
		[dbo].[Customers].[ContactName],
		[dbo].[CustomerCustomerDemo].[CustomerTypeID]
FROM  [dbo].[CustomerCustomerDemo]
INNER JOIN [dbo].[Customers]
ON [dbo].[CustomerCustomerDemo].[CustomerID] = [dbo].[Customers].[CustomerID]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_CustomerDemographics_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_CustomerDemographics_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_CustomerDemographics_SelectAll]

CREATE PROCEDURE [dbo].[PR_CustomerDemographics_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[CustomerDemographics].[CustomerTypeID],
		[dbo].[CustomerDemographics].[CustomerDesc]
FROM  [dbo].[CustomerDemographics]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Customers_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Customers_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Customers_SelectAll]

CREATE PROCEDURE [dbo].[PR_Customers_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Customers].[CustomerID],
		[dbo].[Customers].[CompanyName],
		[dbo].[Customers].[ContactName],
		[dbo].[Customers].[ContactTitle],
		[dbo].[Customers].[Address],
		[dbo].[Customers].[City],
		[dbo].[Customers].[Region],
		[dbo].[Customers].[PostalCode],
		[dbo].[Customers].[Country],
		[dbo].[Customers].[Phone],
		[dbo].[Customers].[Fax]
FROM  [dbo].[Customers]

ORDER BY [dbo].[Customers].[CompanyName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Employees_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Employees_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Employees_SelectAll]

CREATE PROCEDURE [dbo].[PR_Employees_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Employees].[EmployeeID],
		[dbo].[Employees].[LastName] AS [Employees_LastName],
		[dbo].[Employees].[FirstName] AS [Employees_FirstName],
		[dbo].[Employees].[Title],
		[dbo].[Employees].[TitleOfCourtesy],
		[dbo].[Employees].[BirthDate],
		[dbo].[Employees].[HireDate],
		[dbo].[Employees].[Address],
		[dbo].[Employees].[City],
		[dbo].[Employees].[Region],
		[dbo].[Employees].[PostalCode],
		[dbo].[Employees].[Country],
		[dbo].[Employees].[HomePhone],
		[dbo].[Employees].[Extension],
		[dbo].[Employees].[Photo],
		[dbo].[Employees].[Notes],
		[dbo].[Employees].[ReportsTo],
		[ReportsTo_Employees].[LastName] AS [ReportsTo_Employees_LastName],
		[ReportsTo_Employees].[FirstName] AS [ReportsTo_Employees_FirstName],
		[dbo].[Employees].[PhotoPath]
FROM  [dbo].[Employees]
LEFT OUTER JOIN [dbo].[Employees] AS [ReportsTo_Employees]
ON [dbo].[Employees].[ReportsTo] = [ReportsTo_Employees].[EmployeeID]

ORDER BY [Employees_FirstName],
		[Employees_LastName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_EmployeeTerritories_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_EmployeeTerritories_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_EmployeeTerritories_SelectAll]

CREATE PROCEDURE [dbo].[PR_EmployeeTerritories_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[EmployeeTerritories].[EmployeeID],
		[dbo].[Employees].[LastName],
		[dbo].[Employees].[FirstName],
		[dbo].[EmployeeTerritories].[TerritoryID],
		[dbo].[Territories].[TerritoryDescription]
FROM  [dbo].[EmployeeTerritories]
INNER JOIN [dbo].[Employees]
ON [dbo].[EmployeeTerritories].[EmployeeID] = [dbo].[Employees].[EmployeeID]
INNER JOIN [dbo].[Territories]
ON [dbo].[EmployeeTerritories].[TerritoryID] = [dbo].[Territories].[TerritoryID]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Invoices_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Invoices_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Invoices_SelectAll]

CREATE PROCEDURE [dbo].[PR_Invoices_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Invoices].[ShipName],
		[dbo].[Invoices].[ShipAddress],
		[dbo].[Invoices].[ShipCity],
		[dbo].[Invoices].[ShipRegion],
		[dbo].[Invoices].[ShipPostalCode],
		[dbo].[Invoices].[ShipCountry],
		[dbo].[Invoices].[CustomerID],
		[dbo].[Invoices].[CustomerName],
		[dbo].[Invoices].[Address],
		[dbo].[Invoices].[City],
		[dbo].[Invoices].[Region],
		[dbo].[Invoices].[PostalCode],
		[dbo].[Invoices].[Country],
		[dbo].[Invoices].[Salesperson],
		[dbo].[Invoices].[OrderID],
		[dbo].[Invoices].[OrderDate],
		[dbo].[Invoices].[RequiredDate],
		[dbo].[Invoices].[ShippedDate],
		[dbo].[Invoices].[ShipperName],
		[dbo].[Invoices].[ProductID],
		[dbo].[Invoices].[ProductName],
		[dbo].[Invoices].[UnitPrice],
		[dbo].[Invoices].[Quantity],
		[dbo].[Invoices].[Discount],
		[dbo].[Invoices].[ExtendedPrice],
		[dbo].[Invoices].[Freight]
FROM  [dbo].[Invoices]

ORDER BY [dbo].[Invoices].[OrderDate],
		[dbo].[Invoices].[CustomerName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Order Details_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Order Details_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Order Details_SelectAll]

CREATE PROCEDURE [dbo].[PR_Order Details_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Order Details].[OrderID],
		[dbo].[Order Details].[ProductID],
		[dbo].[Products].[ProductName],
		[dbo].[Order Details].[UnitPrice],
		[dbo].[Order Details].[Quantity],
		[dbo].[Order Details].[Discount]
FROM  [dbo].[Order Details]
INNER JOIN [dbo].[Products]
ON [dbo].[Order Details].[ProductID] = [dbo].[Products].[ProductID]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Order Details Extended_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Order Details Extended_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Order Details Extended_SelectAll]

CREATE PROCEDURE [dbo].[PR_Order Details Extended_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Order Details Extended].[OrderID],
		[dbo].[Order Details Extended].[ProductID],
		[dbo].[Order Details Extended].[ProductName],
		[dbo].[Order Details Extended].[UnitPrice],
		[dbo].[Order Details Extended].[Quantity],
		[dbo].[Order Details Extended].[Discount],
		[dbo].[Order Details Extended].[ExtendedPrice]
FROM  [dbo].[Order Details Extended]

ORDER BY [dbo].[Order Details Extended].[ProductName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Order Subtotals_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Order Subtotals_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Order Subtotals_SelectAll]

CREATE PROCEDURE [dbo].[PR_Order Subtotals_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Order Subtotals].[OrderID],
		[dbo].[Order Subtotals].[Subtotal]
FROM  [dbo].[Order Subtotals]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Orders_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Orders_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Orders_SelectAll]

CREATE PROCEDURE [dbo].[PR_Orders_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Orders].[OrderID],
		[dbo].[Orders].[CustomerID],
		[dbo].[Customers].[CompanyName] AS [Customers_CompanyName],
		[dbo].[Customers].[ContactName],
		[dbo].[Orders].[EmployeeID],
		[dbo].[Employees].[LastName],
		[dbo].[Employees].[FirstName],
		[dbo].[Orders].[OrderDate],
		[dbo].[Orders].[RequiredDate],
		[dbo].[Orders].[ShippedDate],
		[dbo].[Orders].[ShipVia],
		[dbo].[Shippers].[CompanyName] AS [Shippers_CompanyName],
		[dbo].[Orders].[Freight],
		[dbo].[Orders].[ShipName],
		[dbo].[Orders].[ShipAddress],
		[dbo].[Orders].[ShipCity],
		[dbo].[Orders].[ShipRegion],
		[dbo].[Orders].[ShipPostalCode],
		[dbo].[Orders].[ShipCountry]
FROM  [dbo].[Orders]
LEFT OUTER JOIN [dbo].[Customers]
ON [dbo].[Orders].[CustomerID] = [dbo].[Customers].[CustomerID]
LEFT OUTER JOIN [dbo].[Employees]
ON [dbo].[Orders].[EmployeeID] = [dbo].[Employees].[EmployeeID]
LEFT OUTER JOIN [dbo].[Shippers]
ON [dbo].[Orders].[ShipVia] = [dbo].[Shippers].[ShipperID]

ORDER BY [dbo].[Orders].[OrderDate]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Orders Qry_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Orders Qry_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Orders Qry_SelectAll]

CREATE PROCEDURE [dbo].[PR_Orders Qry_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Orders Qry].[OrderID],
		[dbo].[Orders Qry].[CustomerID],
		[dbo].[Orders Qry].[EmployeeID],
		[dbo].[Orders Qry].[OrderDate],
		[dbo].[Orders Qry].[RequiredDate],
		[dbo].[Orders Qry].[ShippedDate],
		[dbo].[Orders Qry].[ShipVia],
		[dbo].[Orders Qry].[Freight],
		[dbo].[Orders Qry].[ShipName],
		[dbo].[Orders Qry].[ShipAddress],
		[dbo].[Orders Qry].[ShipCity],
		[dbo].[Orders Qry].[ShipRegion],
		[dbo].[Orders Qry].[ShipPostalCode],
		[dbo].[Orders Qry].[ShipCountry],
		[dbo].[Orders Qry].[CompanyName],
		[dbo].[Orders Qry].[Address],
		[dbo].[Orders Qry].[City],
		[dbo].[Orders Qry].[Region],
		[dbo].[Orders Qry].[PostalCode],
		[dbo].[Orders Qry].[Country]
FROM  [dbo].[Orders Qry]

ORDER BY [dbo].[Orders Qry].[OrderDate]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Product Sales for 1997_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Product Sales for 1997_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Product Sales for 1997_SelectAll]

CREATE PROCEDURE [dbo].[PR_Product Sales for 1997_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Product Sales for 1997].[CategoryName],
		[dbo].[Product Sales for 1997].[ProductName],
		[dbo].[Product Sales for 1997].[ProductSales]
FROM  [dbo].[Product Sales for 1997]

ORDER BY [dbo].[Product Sales for 1997].[CategoryName],
		[dbo].[Product Sales for 1997].[ProductName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Products_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Products_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Products_SelectAll]

CREATE PROCEDURE [dbo].[PR_Products_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Products].[ProductID],
		[dbo].[Products].[ProductName],
		[dbo].[Products].[SupplierID],
		[dbo].[Suppliers].[CompanyName],
		[dbo].[Suppliers].[ContactName],
		[dbo].[Products].[CategoryID],
		[dbo].[Categories].[CategoryName],
		[dbo].[Products].[QuantityPerUnit],
		[dbo].[Products].[UnitPrice],
		[dbo].[Products].[UnitsInStock],
		[dbo].[Products].[UnitsOnOrder],
		[dbo].[Products].[ReorderLevel],
		[dbo].[Products].[Discontinued]
FROM  [dbo].[Products]
LEFT OUTER JOIN [dbo].[Categories]
ON [dbo].[Products].[CategoryID] = [dbo].[Categories].[CategoryID]
LEFT OUTER JOIN [dbo].[Suppliers]
ON [dbo].[Products].[SupplierID] = [dbo].[Suppliers].[SupplierID]

ORDER BY [dbo].[Products].[ProductName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Products Above Average Price_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Products Above Average Price_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Products Above Average Price_SelectAll]

CREATE PROCEDURE [dbo].[PR_Products Above Average Price_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Products Above Average Price].[ProductName],
		[dbo].[Products Above Average Price].[UnitPrice]
FROM  [dbo].[Products Above Average Price]

ORDER BY [dbo].[Products Above Average Price].[ProductName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Products by Category_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Products by Category_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Products by Category_SelectAll]

CREATE PROCEDURE [dbo].[PR_Products by Category_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Products by Category].[CategoryName],
		[dbo].[Products by Category].[ProductName],
		[dbo].[Products by Category].[QuantityPerUnit],
		[dbo].[Products by Category].[UnitsInStock],
		[dbo].[Products by Category].[Discontinued]
FROM  [dbo].[Products by Category]

ORDER BY [dbo].[Products by Category].[CategoryName],
		[dbo].[Products by Category].[ProductName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Quarterly Orders_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Quarterly Orders_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Quarterly Orders_SelectAll]

CREATE PROCEDURE [dbo].[PR_Quarterly Orders_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Quarterly Orders].[CustomerID],
		[dbo].[Quarterly Orders].[CompanyName],
		[dbo].[Quarterly Orders].[City],
		[dbo].[Quarterly Orders].[Country]
FROM  [dbo].[Quarterly Orders]

ORDER BY [dbo].[Quarterly Orders].[CompanyName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Region_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Region_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Region_SelectAll]

CREATE PROCEDURE [dbo].[PR_Region_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Region].[RegionID],
		[dbo].[Region].[RegionDescription]
FROM  [dbo].[Region]

ORDER BY [dbo].[Region].[RegionDescription]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Sales by Category_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Sales by Category_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Sales by Category_SelectAll]

CREATE PROCEDURE [dbo].[PR_Sales by Category_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Sales by Category].[CategoryID],
		[dbo].[Sales by Category].[CategoryName],
		[dbo].[Sales by Category].[ProductName],
		[dbo].[Sales by Category].[ProductSales]
FROM  [dbo].[Sales by Category]

ORDER BY [dbo].[Sales by Category].[CategoryName],
		[dbo].[Sales by Category].[ProductName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Sales Totals by Amount_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Sales Totals by Amount_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Sales Totals by Amount_SelectAll]

CREATE PROCEDURE [dbo].[PR_Sales Totals by Amount_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Sales Totals by Amount].[SaleAmount],
		[dbo].[Sales Totals by Amount].[OrderID],
		[dbo].[Sales Totals by Amount].[CompanyName],
		[dbo].[Sales Totals by Amount].[ShippedDate]
FROM  [dbo].[Sales Totals by Amount]

ORDER BY [dbo].[Sales Totals by Amount].[CompanyName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Shippers_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Shippers_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Shippers_SelectAll]

CREATE PROCEDURE [dbo].[PR_Shippers_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Shippers].[ShipperID],
		[dbo].[Shippers].[CompanyName],
		[dbo].[Shippers].[Phone]
FROM  [dbo].[Shippers]

ORDER BY [dbo].[Shippers].[CompanyName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Summary of Sales by Quarter_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Summary of Sales by Quarter_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Summary of Sales by Quarter_SelectAll]

CREATE PROCEDURE [dbo].[PR_Summary of Sales by Quarter_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Summary of Sales by Quarter].[ShippedDate],
		[dbo].[Summary of Sales by Quarter].[OrderID],
		[dbo].[Summary of Sales by Quarter].[Subtotal]
FROM  [dbo].[Summary of Sales by Quarter]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Summary of Sales by Year_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Summary of Sales by Year_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Summary of Sales by Year_SelectAll]

CREATE PROCEDURE [dbo].[PR_Summary of Sales by Year_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Summary of Sales by Year].[ShippedDate],
		[dbo].[Summary of Sales by Year].[OrderID],
		[dbo].[Summary of Sales by Year].[Subtotal]
FROM  [dbo].[Summary of Sales by Year]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Suppliers_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Suppliers_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Suppliers_SelectAll]

CREATE PROCEDURE [dbo].[PR_Suppliers_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Suppliers].[SupplierID],
		[dbo].[Suppliers].[CompanyName],
		[dbo].[Suppliers].[ContactName],
		[dbo].[Suppliers].[ContactTitle],
		[dbo].[Suppliers].[Address],
		[dbo].[Suppliers].[City],
		[dbo].[Suppliers].[Region],
		[dbo].[Suppliers].[PostalCode],
		[dbo].[Suppliers].[Country],
		[dbo].[Suppliers].[Phone],
		[dbo].[Suppliers].[Fax],
		[dbo].[Suppliers].[HomePage]
FROM  [dbo].[Suppliers]

ORDER BY [dbo].[Suppliers].[CompanyName]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GO
/*
This is SP Begining Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM sys.sysobjects WHERE id = object_id(N'[dbo].[PR_Territories_SelectAll]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
		DROP PROCEDURE [dbo].[PR_Territories_SelectAll]
END
GO

/*
-- =============================================
-- Author 	  : Tools4SQL.net - T4S Stored Procedure Generator
-- Create date: 01-March-2011
-- Description:	This stored procedure is generated by T4S Stored Procedure Generator.
-- =============================================
*/

--   [dbo].[PR_Territories_SelectAll]

CREATE PROCEDURE [dbo].[PR_Territories_SelectAll]

/*
This is SP Parameter Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

AS

SET NOCOUNT ON;

/*
This is SP Body Comment generated from Tools4SQL.net - T4S Stored Procedure Generator.
Website : http://www.tools4sql.net
Email : info@tools4sql.net
*/

SELECT  
		[dbo].[Territories].[TerritoryID],
		[dbo].[Territories].[TerritoryDescription],
		[dbo].[Territories].[RegionID],
		[dbo].[Region].[RegionDescription]
FROM  [dbo].[Territories]
INNER JOIN [dbo].[Region]
ON [dbo].[Territories].[RegionID] = [dbo].[Region].[RegionID]

ORDER BY [dbo].[Territories].[TerritoryDescription]

GO
--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~